studybuddy/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login_user, name="login"),
    path('register/', views.register_user, name="register"),
    path('logout/', views.logout_user, name="logout"),
    path('<int:pk>/', views.room, name="room"),
    path('delete-message/', views.delete_message, name="delete-message"),
    path('create-room/', views.create_room, name="create-room"),
    path('profile<int:pk>/', views.profile, name="profile"),
    path('update-room/<int:pk>/', views.update_room, name="update-room"),
    path('delete-room/', views.delete_room, name="delete-room"),
    path('update-profile/', views.update_profile, name="update-profile"),
    path('reply<int:pk>/', views.reply_message, name="reply-message")
]

studybuddy/studybuddy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('studybud/', include('core.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studybuddy/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    participants = models.ManyToManyField(User,
                                          related_name='participants',
                                          blank=True
                                          )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']

    def __str__(self):
        return self.name


class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original_message = models.ForeignKey('Message', on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.body[:100]}...'


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    replies = models.ManyToManyField(Reply, related_name='message_replies', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.body[:100]}...'


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pic/')
    bio = models.CharField(max_length=1000)

    @property
    def image_url(self):
        if self.profile_pic:
            return self. profile_pic.url
        else:
            return 'static/images/images.png'

studybuddy/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . models import UserProfile


class RegisterForm(UserCreationForm):
    username = forms.CharField(label='Username:',
                               max_length=64, required=True)
    email = forms.EmailField(label='Email:',
                             max_length=254, required=True)
    password1 = forms.CharField(label='Password:',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password:',
                                widget=forms.PasswordInput)


class LoginForm(forms.Form):
    username = forms.CharField(label='Username:',
                               max_length=64, required=True)
    password = forms.CharField(label='Password:', widget=forms.PasswordInput)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic', 'bio']
        widgets = {
            'profile_pic': forms.FileInput(attrs={'class': 'custom-file-input'}),
        }

        widgets = {
            'bio': forms.Textarea(attrs={'class': 'bio-textarea'}),
        }

    bio = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'bio-textarea'}),
        error_messages={'required': ''}  # Set the error message to an empty string
    )

    profile_pic = forms.ImageField(
        widget=forms.FileInput(attrs={'class': 'custom-file-input'}),
        error_messages={'required': ''}  # Set the error message to an empty string
    )

studybuddy/core/views.py
import json
from django.shortcuts import render, redirect
from .models import Room, Topic, Message, UserProfile, Reply
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import RegisterForm, LoginForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

# Create your views here.


def login_user(request):
    page = 'login'
    form = LoginForm()
    message = ''
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            username = form.cleaned_data['username']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
        else:
            message = 'Invalid Username/Password'

    context = {
        'page': page,
        'form': form,
        'message': message,
    }

    return render(request, 'core/login-register.html', context)


def register_user(request):
    page = 'register'
    message = ''
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = User.objects.create_user(username, email, password)
            user_profile = UserProfile.objects.create(user=user)
            return redirect('login')
        else:
            message = 'Invalid Details'

    context = {
        'form': form,
        'page': page,
        'message': message,

    }
    return render(request, 'core/login-register.html', context)


def logout_user(request):
    logout(request)
    return redirect('index')


def index(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ""
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    topics = Topic.objects.all()
    rooms_count = rooms.count()
    topics_count = topics.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    user_profile = None
    if request.user.is_authenticated:
        if request.user.userprofile:
            user_profile = UserProfile.objects.get(user=request.user)
        else:
            user_profile = None

    form = ProfileForm(request.POST, request.FILES, instance=user_profile)
    context = {
        "rooms": rooms,
        "topics": topics,
        "rooms_count": rooms_count,
        "topics_count": topics_count,
        "room_messages": room_messages,
        "form": form,
    }
    return render(request, 'core/index.html', context)


@login_required(login_url='login')
def room(request, pk):
    user_profile = UserProfile.objects.get(user=request.user)
    form = ProfileForm(request.POST, request.FILES, instance=user_profile)
    topics = Topic.objects.all()
    topics_count = topics.count()
    the_room = Room.objects.get(pk=pk)
    room_messages = Message.objects.filter(room=the_room)
    participants = the_room.participants.all()
    if request.method == "POST":
        body = request.POST.get('message')
        message = Message.objects.create(user=request.user,
                                         room=the_room,
                                         body=body)
        the_room.participants.add(request.user)
        return redirect('room', pk=the_room.id)

    context = {
        "the_room": the_room,
        "room_messages": room_messages,
        "participants": participants,
        "topics_count": topics_count,
        "topics": topics,
        "form": form,

    }
    return render(request, 'core/the room.html', context)


def delete_message(request):
    if request.method == 'POST':
        message_id = request.POST.get('delete-message')
        message = Message.objects.get(id=message_id)
        message.delete()

    return redirect('room', pk=message.room.id)


@login_required(login_url='login')
def create_room(request):
    if request.method == "POST":
        name = request.POST.get('name')
        topic = request.POST.get('topic')
        description = request.POST.get('description')
        existing_topic = Topic.objects.filter(name=topic).first()

        if existing_topic:
            topic = existing_topic
        else:
            topic = Topic.objects.create(name=topic)
        new_room = Room.objects.create(
            host=request.user,
            topic=topic,
            name=name,
            description=description
        )
        return JsonResponse({'success': True,
                             'message': 'Room created successfully'})

    return redirect('index')


@login_required(login_url='login')
def profile(request, pk):
    user_profile = UserProfile.objects.get(user=request.user)
    form = ProfileForm(request.POST, request.FILES, instance=user_profile)
    user = User.objects.get(pk=pk)
    user_profile = UserProfile.objects.get(user=user)
    rooms = Room.objects.filter(host=user)
    messages = Message.objects.filter(user=user)
    topics = Topic.objects.all()
    topics_count = topics.count()

    context = {
        "user_profile": user_profile,
        "user": user,
        "rooms": rooms,
        "messages": messages,
        "topics_count": topics_count,
        "topics": topics,
        "form": form,
    }

    return render(request, 'core/profile.html', context)


def update_room(request, pk):
    room = Room.objects.get(pk=pk)

    if request.method == "POST":
        try:
            room.name = request.POST.get('name')
            room.description = request.POST.get('description')

            # Get the topic data by name, assuming you're sending the topic name in the form
            topic_name = request.POST.get('topic')
            existing_topic = Topic.objects.filter(name=topic_name).first()
            if existing_topic:
                room.topic = existing_topic
            else:
                new_topic = Topic.objects.create(name=topic_name)
                room.topic = new_topic

            room.save()

            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)})

    topic_data = {
        'id': room.topic.id,
        'name': room.topic.name,

    }
    room_data = {
        'name': room.name,
        'topic': topic_data,  # Include the topic data
        'description': room.description,
    }
    return JsonResponse({
        'success': True,
        'room': room_data,
    })


def delete_room(request):
    if request.method == 'POST':
        room_id = request.POST.get('delete-room')
        room = Room.objects.get(id=room_id)
        room.delete()

    return redirect('index')


@login_required(login_url='login')
def update_profile(request):
    if request.method == 'POST':
       form = ProfileForm(request.POST, request.FILES, instance=request.user.userprofile)
       if form.is_valid():
           form.save()
           return JsonResponse({'success': True})

    return JsonResponse({'success': False, 'errors': form.errors}, status=400)


def reply_message(request, pk):
    message = get_object_or_404(Message, pk=pk)
    if request.method == "POST":
        reply_body = request.POST.get('reply')
        reply = Reply.objects.create(user=request.user, original_message=message, body=reply_body)
        message.replies.add(reply)

    return redirect('room', pk=message.room.id)

studybuddy/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Study Buddy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/base.css' %}"/>
    <link rel="stylesheet" href="{% static 'styles/index.css' %}"/>
    <link rel="stylesheet" href="{% static 'styles/profile.css' %}"/>
    <link rel="stylesheet" href="{% static 'styles/room.css' %}"/>
    <script src="https://kit.fontawesome.com/b55419cd6c.js"
            crossorigin="anonymous"></script>
    <script>
        let user = "{{request.user}}";
    </script>
</head>
<body>
    <nav>
        <div class="nav-container">
            <div class="topics-container">
                <div class="topics__content">
                    <div class="logo">
                        <i class="fa-solid fa-xmark close-topics"></i>
                        <a href="{% url 'index' %}">
                            <img src="{% static 'images/favicon.ico' %}"/>
                            <h1>Study Buddy</h1>
                        </a>
                    </div>
                    <h1>Browse Topics</h1>
                    <div class="topics">
                        <ul>
                             <li>
                                <a href="{% url 'index' %}">All</a>
                                <p>{{topics_count}}</p>
                            </li>
                            {% for topic in topics %}
                            <li>
                                <a href="{% url 'index' %}?q={{topic.name}}">{{topic.name}}</a>
                                <p>{{topic.room_set.all.count}}</p>
                            </li>
                            {% endfor %}
                        </ul>

                    </div>

                    <div class="settings">
                        <div>
                            <span>
                                <i class="fa-solid fa-gear"></i>
                                <p>Settings</p>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="logo">
                 <i class="fa-solid fa-bars open-topics"></i>
                <a href="{% url 'index' %}">
                    <img src="{% static 'images/favicon.ico' %}"/>
                    <h1>Study Buddy</h1>
                </a>
            </div>
            <div class="search-bar">
                    <form method="GET" action="{% url 'index' %}" id="searchbar">
                        <label>
                          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                            <title>search</title>
                                <path
                                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                                ></path>
                          </svg>
                          <input type="text" name="q" placeholder="Search for rooms....."/>

                        </label>
                    </form>

            </div>
            <div class="links">
                 {% if user.is_authenticated %}
                     <a class="profile-link" href="{% url 'profile' request.user.id %}">
                        <img src="{{ request.user.userprofile.image_url }}">
                        <p>@{{request.user.username}}</p>
                    </a>

                {% else %}
                     <a class="profile-link" href="#">
                        <img src="{% static 'images/images.png' %}">
                        <p>Guest</p>
                    </a>

                {% endif %}

                {% if user.is_authenticated %}
                 <a class="login" href="{% url 'logout' %}">
                    Logout
                </a>
                {% else %}
                <a class="login" href="{% url 'login' %}">
                    Login/Register
                </a>
                {% endif %}

            </div>

        </div>
    </nav>
    {% block content %}


    {% endblock content %}
    <div class="profile-overlay">
        <div class="profile-content">
            <div>
                <i class="fa-solid fa-arrow-left close-profile "></i>
                <h4>Create/Update Profile</h4>
            </div>

            <form class="profile-form" method="POST" action="{% url 'update-profile' %}">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Submit</button>
            </form>

        </div>

    </div>
    <script >
        // opening and closing the navigation bar
        const openBtn = document.querySelector('.open-topics');
        const closeBtn = document.querySelector('.close-topics');
        const topicsContainer = document.querySelector('.topics-container');

        openBtn.addEventListener('click', function() {
            console.log('open')
            topicsContainer.style.left = '0'; // Corrected with quotes around '0'
        });

        closeBtn.addEventListener('click', function() {
            console.log('close')
            topicsContainer.style.left = '-300px'; // Corrected with quotes around '-300px'
        });

        // updating the profile pic

        const settings = document.querySelector('.settings');
        const closeProfile = document.querySelector('.close-profile');
        const profileUpdate = document.querySelector('.profile-overlay');

        settings.addEventListener('click', function(event) {
            event.preventDefault();
            profileUpdate.style.display = "block"
        });

         closeProfile.addEventListener('click', function(event) {
            event.preventDefault();
            profileUpdate.style.display = "none"
        });

         const profileForm = document.querySelector('.profile-form');
         profileForm.addEventListener('submit', function(event) {
            event.preventDefault();
            const formData = new FormData(profileForm);
            const url = "/studybud/update-profile/"

            fetch( url, {
                method: 'POST',
                body: formData,
            })

           .then((response) => {
                console.log(response);
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })

           .then((data) => {
                console.log(data)
                if (data.success) {
                    console.log('Success')
                    profileUpdate.style.display = "none";
                    window.location.reload();
                    profileForm.reset();
                };
            })
         })
    </script>
</body>
</html>

studybuddy/templates/core/index.html
<!DOCTYPE html>
{% extends 'core/base.html'%}
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'styles/index.css' %}"/>
    <script src="https://kit.fontawesome.com/b55419cd6c.js"
            crossorigin="anonymous"></script>
</head>
<body>
    {% block content %}
    <section class="home-container">
        <div class="home__content">
             <div class="rooms-container">
                 <div class="rooms__header">
                     <div class="rooms__count">
                         <h2>Study Rooms</h2>
                         <small>{{rooms_count}} Rooms Available</small>
                     </div>
                     <div class="rooms__create">
                         <a  class="create-room" href="#">
                             <i class="fa-solid fa-plus"></i>
                             <p>Create</p>
                         </a>
                     </div>

                 </div>
                 <div class="rooms">
                     <ul>
                       {% for room in rooms %}
                       <li>
                          <div class="details">
                              <a href="{% url 'profile' room.host.userprofile.user.id %}">
                                  <img src="{% if room.host.userprofile.profile_pic %}{{ room.host.userprofile.image_url }}{% else %}{% static 'images/images.png' %}{% endif %}"/>
                                  <p>@{{room.host.username}}</p>
                              </a>
                              <small>{{room.created_at|timesince}}</small>
                          </div>
                           <div class="room__name">
                               <a href="{% url 'room' room.id %}">{{room.name}}</a>
                           </div>
                           <hr>
                           <div class="room__topic">
                               <small>{{room.participants.all.count}} joined</small>
                               <p>{{room.topic}}</p>
                           </div>
                       </li>

                       {% endfor %}
                     </ul>
                 </div>

            </div>

            <div class="activity-container">
                <div class="activity__content">
                    <h2>Recent Activity</h2>
                    <div class="activity">
                        <ul>
                            {% for message in room_messages %}
                            <li>
                                <div class="activity__user">
                                    <a href="{% url 'profile' message.user.userprofile.user.id %}">
                                      <img src="{% if message.user.userprofile.profile_pic %}{{ message.user.userprofile.image_url }}{% else %}{% static 'images/images.png' %}{% endif %}"/>
                                      <p>@{{message.user.username}}</p>
                                    </a>
                                    <small>{{message.created_at|timesince}}</small>
                                </div>

                                <div class="activity__room">
                                    <a href="{% url 'room' message.room.id %}">replied to <span>"{{message.room.name}}"</span></a>
                                </div>
                                <div class="activity__message">
                                    <p>{{message}}</p>
                                </div>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>

                </div>

            </div>

        </div>
    </section>
    <div class="create-room-overlay">
        <div class="create-room__content">
            <div class="create-room-form">
                <div>
                     <h5>Create Room</h5>
                    <i class="fa-solid fa-xmark close-create-room"></i>
                </div>

                <form class="create-form" method="POST" action="/studybud/create-room">
                    {% csrf_token %}
                    <input type="text" name="name" placeholder="Room name.."/>
                    <input type="text" name="topic" placeholder="Topic name..."/>
                    <textarea name="description" placeholder="description"></textarea>
                    <button type="text">Submit</button>
                </form>
            </div>

        </div>

    </div>
    <script>
         // create room

        const form = document.querySelector('.create-form');
        const createLink = document.querySelector('.create-room');
        const closeForm = document.querySelector('.close-create-room');
        const createRoomOverlay = document.querySelector(".create-room-overlay");

        createLink.addEventListener('click', function(event){
            event.preventDefault();
            console.log('Working')
            createRoomOverlay.style.display = "block";
        });

        closeForm.addEventListener('click', function(event){
            event.preventDefault();
            createRoomOverlay.style.display = "none";
        });


        form.addEventListener('submit', function(event) {
            event.preventDefault();
            const formData  = new FormData(form);
            url = "/studybud/create-room/"

            fetch(url, {
                method: "POST",
                body: formData,
            })

            .then((response) => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then((data) => {
                if (data.success) {
                    console.log('Success')
                    createRoomOverlay.style.display = "none";
                    window.location.reload();
                    form.reset();
                };
            })
        });
    </script>

{% endblock %}

studybuddy/templates/core/login-register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Study Buddy</title>
        <link rel="stylesheet" href="{% static 'styles/login.css' %}"/>
    </head>
    <body>
        <div class="container">
            <div class="logo">
                <img src="{% static 'images/favicon.ico'%}"/>
                <h1>Study Buddy</h1>
            </div>

            {% if page == 'login' %}
            <div class="login-form">
                {% if message %}
                    {{message}}
                {% endif %}
                <h1>Login</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Login</button>
                </form>
                <p>Not yet Registered??</p>
                <a href="{% url 'register' %}">Sign Up</a>

            </div>
            {% else%}
            <div class="login-form">
                {% if message %}
                    {{message}}
                {% endif %}
                <h1>Register</h1>
                 <form method="POST" action="">
                     {% csrf_token %}
                     {{form.as_p}}
                     <button class="reg-btn" type="submit">Register</button>
                </form>
                 <p>Already Registered??</p>
                <a href="{% url 'login' %}">Sign In</a>
            </div>
            {% endif %}
        </div>

    </body>
</html>